### PR TITLE
Add Project.toml File

### PR DESCRIPTION
**Pull request by ccoffrin**
Updates for new package manager and tag bot.

### CODE REVIEW

**Comment by mlubin** [comment]
I'm only a minor contributor to Pavito :)

**Comment by ccoffrin** [comment]
By my assessment it was a two-way tie between you and Emrey, and you are still active in the community. :-)

**Comment by chriscoey** [comment]
MOI and JuMP don't have author lines

**Comment by ccoffrin** [comment]
We can remove it, what every you guys want is fine by me.

**Pull request merged**
