### PR TITLE
Fix readme

### PR DESCRIPTION
**Pull request by ericphanson**
I was reading the READMEs of Pajarito and Pavito and was getting confused about the difference between them-- I think all the references to convex programming here are actually supposed to be for non-linear programming, so I gave fixing it a try.

### CODE REVIEW

**Comment by chriscoey** [comment]
Although Pavito can be called on MINLPs, it does not "technically" solve MINLPs, which are more general than MICPs (C for convex), though it may be able to find local solutions for MINLPs. 

Can you elaborate on what you find confusing? We do explain what we mean by MICP, and we do mention that this is a NLP-solver-based algorithm.

**Comment by ericphanson** [comment]
Ah ok, sorry then. What was confusing to me is that the first few sentences of Pavito and Pajarito's README's are almost exactly the same:

> Pavito is a mixed-integer convex programming (MICP) solver package written in Julia. MICP problems are convex except for restrictions that some variables take binary or integer values.
>
>Pavito solves MICP problems by constructing sequential polyhedral outer-approximations of the convex feasible set, similar to Bonmin.

vs Pajarito:

> Pajarito is a mixed-integer convex programming (MICP) solver package written in Julia. MICP problems are convex except for restrictions that some variables take binary or integer values.
>
>Pajarito solves MICP problems by constructing sequential polyhedral outer-approximations of the convex feasible set, similar to Bonmin.

It seemed strange for there to be two packages solving the same kind of problems with the same technique, and I figured that was a copy-paste error or something like that. More specifically, since the description for Pavito says

>A gradient-based outer approximation solver for convex mixed-integer nonlinear programming (MINLP)

I figured that the MICP stuff in Pavito's README was supposed to be MINLP instead.

**Comment by chriscoey** [comment]
Yes they were originally the same package but we split them out. We could be more explicit in the readme that Pajarito uses conic solvers and Pavito uses NLP solvers.

**Comment by ericphanson** [comment]
I see, makes sense. I'm not quite sure how to improve the README then, so I'll close this.

**Pull request closed without merging**
