### PR TITLE
Update appveyor.yml

### LINKED ISSUE #13: AppVeyor is failing
Switch to a modern AppVeyor script like https://github.com/JuliaOpt/Clp.jl/blob/master/appveyor.yml.

### PR DESCRIPTION
**Pull request by mlubin**
Closes #13

### CODE REVIEW

**Comment by mlubin** [comment]
FYI there's still a failure on Julia 1.0 x86. If you don't care about it, mark it as an allowed failure. It's not good to leave CI in a failing state.

**Comment by chriscoey** [comment]
do we need to run x86?

**Comment by mlubin** [comment]
The rest of the JuliaOpt ecosystem is generally passing tests on x86. It's a good sanity check that you haven't misused `Int`, `Int32`, and `Int64`. There might be some person in the future who tries to run Pavito on a 32-bit system, up to you if you care to support it. It's not a big deal either way; it's worse to have CI failing for a known reason that you don't intend to fix very quickly.

**Comment by chriscoey** [comment]
I'll see if #15 fixes it

**Pull request merged**
